import os
import json
from pptx import Presentation

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../..", "data", "generated_outputs"))

def generate_pptx_report(filename: str, title: str, slides_json_str: str) -> str:
    """
    Generates a PowerPoint presentation (.pptx).
    slides_json_str must be a stringified list of dictionaries:
    '[{"title": "Slide 1", "content": "Bullet 1\\nBullet 2"}]'
    """
    os.makedirs(BASE_DIR, exist_ok=True)
    
    if not filename.endswith(".pptx"):
        filename += ".pptx"
    file_path = os.path.join(BASE_DIR, os.path.basename(filename))
    
    try:
        slides_data = json.loads(slides_json_str)
        prs = Presentation()
        
        # Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        slide.shapes.title.text = title
        slide.placeholders[1].text = "Generated by Forge Sovereign Workbench"
        
        # Content Slides
        bullet_slide_layout = prs.slide_layouts[1]
        for slide_info in slides_data:
            slide = prs.slides.add_slide(bullet_slide_layout)
            shapes = slide.shapes
            shapes.title.text = slide_info.get("title", "Untitled Slide")
            body_shape = shapes.placeholders[1]
            tf = body_shape.text_frame
            tf.text = slide_info.get("content", "")
            
        prs.save(file_path)
        return f"Success: PowerPoint file generated and saved at {file_path}"
        
    except json.JSONDecodeError:
        return "Error: slides_json_str could not be parsed as valid JSON."
    except Exception as e:
        return f"Error generating PowerPoint file: {str(e)}"